### ISSUE TITLE
Why does a github token need to be specified? 

### ISSUE THREAD

**Issue by Daltz333** [eine/tip#158]
See https://github.com/stefanzweifel/git-auto-commit-action which does not need a github_token

**Comment by eine** [comment]
Hi @Daltz333, the functionalities of **git-auto-commit-action** and **tip** are very different:

The purpose of **git-auto-commit-action** is to write some changes as a commit and then push it to the repo. It feels to me that git-auto-commit-action made sense when actions/checkout was in v1, but it is redundant since actions/checkout@v2 is available:

```sh
git config --local user.email 'GHA@GHA'
git config --local user.name 'GHA'
git commit -am 'message'
git push -u origin +HEAD:"$BRANCH"
``` 

On the other hand, the purpose of **tip** is to push/attach some files/artifacts/assets to a GitHub Release. It is not possible to do it through plain git. In fact, I believe that SSH keys are not valid for this purpose. Other similar tools (e.g. github/hub) need a token too (see https://github.com/github/hub#github-actions). Furthermore, in https://github.com/stefanzweifel/git-auto-commit-action#commits-of-this-action-do-not-trigger-new-workflow-runs and https://github.com/stefanzweifel/git-auto-commit-action#push-to-protected-branches using a PAT is explained. Nevertheless, I believe that actions/checkout@v2 allows to push to protected branches.

This Action uses a token to force-push the git tag (see https://github.com/eine/tip/blob/master/tip.py#L150). Strictly, that is NOT required, and it could be achieved through `git push origin +"$tag"`. However, all other interactions with the API do require a token. Since we have it anyway, it is reused for force-pushing.

Note that the purpose of this Action is to update the assets of GitHub Release located in the same repo where the workflow is executed. Pushing artifacts/assets to other repos is not supported. Hence, the default `GITHUB_TOKEN` suffices; it is not required to create a PAT.
